# Generated by Django 4.1.3 on 2023-12-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightclub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
